services:
  oko:
    build: .
    container_name: oko
    restart: unless-stopped
    environment:
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - PUSHOVER_USER=${PUSHOVER_USER}
    volumes:
      - ./services.toml:/data/services.toml:ro
    command:
      - --config-path=/data/services.toml
      - --interval-seconds=60
